### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Grim-reap3r** [UrekD/Steam-Workshop-Monitor#1]
Hello.

All my workshop checks have same problem.

https://prnt.sc/J0BbI1MQESkU

**Comment by UrekD** [comment]
Hello @Grim-reap3r ,

Sorry to see you are having trouble running the bot. Please insure you have installed all the required packages, running Python 3.10 or later and that config is accessible by the user which the script is run as especially if you are in Linux system. Also that [Steam API](https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/) is accessible, if you open it in browser it will say "Method Not Allowed This API must be called with a HTTP POST request".
