### ISSUE TITLE
Suggestion (sorry for the bother)

### ISSUE THREAD

**Issue by Longshot133** [UrekD/Steam-Workshop-Monitor#15]
Would it be possible to have an option for using steam collections (or html's though idk if thatd be harder)
as adding all the mods individually is a bit annoying when you have over 50 XD.

sorry for the bother figured i'd ask. ty for this mod so much.

**Comment by UrekD** [comment]
Hey as per readme, bot is no longer in development, no new features, only bug fixes. This feature was planned before discontinuation so there is already a method available in the code for parsing a steam collection if someone else ever picks it up.

**Comment by Longshot133** [comment]
gotcha, sorry for the bother and thank you for the reply.

**Comment by UrekD** [comment]
> gotcha, sorry for the bother and thank you for the reply.

No need happy to help, have a nice day :)
